// Copyright (c) 2020-2021 ginlo.net GmbH

package eu.ginlo_apps.ginlo.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table CHANNEL_CATEGORY.
 */
public class ChannelCategory
        implements java.io.Serializable {

    private Long id;

    private String ident;

    private String titleKey;

    private String imageKey;

    private String items;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ChannelCategory() {
    }

    public ChannelCategory(Long id) {
        this.id = id;
    }

    public ChannelCategory(Long id,
                           String ident,
                           String titleKey,
                           String imageKey,
                           String items) {
        this.id = id;
        this.ident = ident;
        this.titleKey = titleKey;
        this.imageKey = imageKey;
        this.items = items;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdent() {
        return ident;
    }

    public void setIdent(String ident) {
        this.ident = ident;
    }

    public String getTitleKey() {
        return titleKey;
    }

    public void setTitleKey(String titleKey) {
        this.titleKey = titleKey;
    }

    public String getImageKey() {
        return imageKey;
    }

    public void setImageKey(String imageKey) {
        this.imageKey = imageKey;
    }

    public String getItems() {
        return items;
    }

    public void setItems(String items) {
        this.items = items;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END
}
