// Copyright (c) 2020-2021 ginlo.net GmbH

package eu.ginlo_apps.ginlo.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import eu.ginlo_apps.ginlo.greendao.Device;
import eu.ginlo_apps.ginlo.model.constant.NumberConstants;
import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table CONTACT.
 */
public class DeviceDao
        extends AbstractDao<eu.ginlo_apps.ginlo.greendao.Device, Long> {

    public static final String TABLENAME = "DEVICE";

    public DeviceDao(DaoConfig config) {
        super(config);
    }

    public DeviceDao(DaoConfig config,
                     AbstractDaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db,
                                   boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";

        db.execSQL("CREATE TABLE " + constraint + "'" + TABLENAME + "' ("  //
                + "'_id' INTEGER PRIMARY KEY ,"  // 0: id
                + "'GUID' TEXT,"  // 1: guid
                + "'ACCOUNT_GUID' TEXT,"  // 2: accountGuid
                + "'ENCRYPTED_DATA' BLOB,"  // 3: encryptedData
                + "'IV' BLOB," // 4: iv
                + "'PUBLIC_KEY' TEXT,"  // 5: publicKey
                + "'OWN_DEVICE' INTEGER,"  // 6: ownDevice
                + "'ATTRIBUTES' TEXT" // 7: attributes
                + ");");
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db,
                                 boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'" + TABLENAME + "'";

        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt,
                              eu.ginlo_apps.ginlo.greendao.Device entity) {
        stmt.clearBindings();
        entity.beforeSafe();

        Long id = entity.getId();

        if (id != null) {
            stmt.bindLong(NumberConstants.INT_1, id);
        }

        String guid = entity.getGuid();

        if (guid != null) {
            stmt.bindString(NumberConstants.INT_2, guid);
        }

        String accountGuid = entity.getAccountGuid();

        if (accountGuid != null) {
            stmt.bindString(NumberConstants.INT_3, accountGuid);
        }

        byte[] encryptedData = entity.getEncryptedData();

        if (encryptedData != null) {
            stmt.bindBlob(NumberConstants.INT_4, encryptedData);
        }

        byte[] iv = entity.getIv();

        if (iv != null) {
            stmt.bindBlob(NumberConstants.INT_5, iv);
        }

        String publicKey = entity.getPublicKey();

        if (publicKey != null) {
            stmt.bindString(NumberConstants.INT_6, publicKey);
        }

        Boolean ownDevice = entity.getOwnDevice();

        if (ownDevice != null) {
            stmt.bindLong(NumberConstants.INT_7, ownDevice ? 1L : 0L);
        }

        String attributes = entity.getAttributes();

        if (attributes != null) {
            stmt.bindString(NumberConstants.INT_8, attributes);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor,
                        int offset) {
        return cursor.isNull(offset + NumberConstants.INT_0) ? null : cursor.getLong(offset + NumberConstants.INT_0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public eu.ginlo_apps.ginlo.greendao.Device readEntity(Cursor cursor,
                                                         int offset) {
        eu.ginlo_apps.ginlo.greendao.Device entity = new eu.ginlo_apps.ginlo.greendao.Device(  //
                cursor.isNull(offset + NumberConstants.INT_0) ? null : cursor.getLong(offset + NumberConstants.INT_0),  // id
                cursor.isNull(offset + NumberConstants.INT_1) ? null : cursor.getString(offset + NumberConstants.INT_1),  // guid
                cursor.isNull(offset + NumberConstants.INT_2) ? null : cursor.getString(offset + NumberConstants.INT_2),  // accountGuid
                cursor.isNull(offset + NumberConstants.INT_3) ? null : cursor.getBlob(offset + NumberConstants.INT_3),  // encryptedData
                cursor.isNull(offset + NumberConstants.INT_4) ? null : cursor.getBlob(offset + NumberConstants.INT_4),  // iv
                cursor.isNull(offset + NumberConstants.INT_5) ? null : cursor.getString(offset + NumberConstants.INT_5),  // publicKey
                cursor.isNull(offset + NumberConstants.INT_6) ? null : (cursor.getShort(offset + NumberConstants.INT_6) != 0),  // ownDevice
                cursor.isNull(offset + NumberConstants.INT_7) ? null : cursor.getString(offset + NumberConstants.INT_7)  // attributes
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor,
                           eu.ginlo_apps.ginlo.greendao.Device entity,
                           int offset) {
        entity.setId(cursor.isNull(offset + NumberConstants.INT_0) ? null : cursor.getLong(offset + NumberConstants.INT_0));
        entity.setGuid(cursor.isNull(offset + NumberConstants.INT_1) ? null : cursor.getString(offset + NumberConstants.INT_1));
        entity.setAccountGuid(cursor.isNull(offset + NumberConstants.INT_2) ? null : cursor.getString(offset + NumberConstants.INT_2));
        entity.setEncryptedData(cursor.isNull(offset + NumberConstants.INT_3) ? null : cursor.getBlob(offset + NumberConstants.INT_3));
        entity.setIv(cursor.isNull(offset + NumberConstants.INT_4) ? null : cursor.getBlob(offset + NumberConstants.INT_4));
        entity.setPublicKey(cursor.isNull(offset + NumberConstants.INT_5) ? null : cursor.getString(offset + NumberConstants.INT_5));
        entity.setOwnDevice(cursor.isNull(offset + NumberConstants.INT_6) ? null : (cursor.getShort(offset + NumberConstants.INT_6) != 0));
        entity.setAttributes(cursor.isNull(offset + NumberConstants.INT_7) ? null : cursor.getString(offset + NumberConstants.INT_7));
    }

    @Override
    protected void bindValues(DatabaseStatement stmt, eu.ginlo_apps.ginlo.greendao.Device entity) {
        stmt.clearBindings();
        entity.beforeSafe();

        Long id = entity.getId();

        if (id != null) {
            stmt.bindLong(NumberConstants.INT_1, id);
        }

        String guid = entity.getGuid();

        if (guid != null) {
            stmt.bindString(NumberConstants.INT_2, guid);
        }

        String accountGuid = entity.getAccountGuid();

        if (accountGuid != null) {
            stmt.bindString(NumberConstants.INT_3, accountGuid);
        }

        byte[] encryptedData = entity.getEncryptedData();

        if (encryptedData != null) {
            stmt.bindBlob(NumberConstants.INT_4, encryptedData);
        }

        byte[] iv = entity.getIv();

        if (iv != null) {
            stmt.bindBlob(NumberConstants.INT_5, iv);
        }

        String publicKey = entity.getPublicKey();

        if (publicKey != null) {
            stmt.bindString(NumberConstants.INT_6, publicKey);
        }

        Boolean ownDevice = entity.getOwnDevice();

        if (ownDevice != null) {
            stmt.bindLong(NumberConstants.INT_7, ownDevice ? 1L : 0L);
        }

        String attributes = entity.getAttributes();

        if (attributes != null) {
            stmt.bindString(NumberConstants.INT_8, attributes);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(eu.ginlo_apps.ginlo.greendao.Device entity,
                                        long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(eu.ginlo_apps.ginlo.greendao.Device entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected boolean hasKey(Device entity) {
        return entity != null && entity.getId() != null;
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity Contact.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {

        public static final Property Id = new Property(NumberConstants.INT_0, Long.class, "id", true, "_id");

        public static final Property Guid = new Property(NumberConstants.INT_1, String.class, "guid", false, "GUID");

        public static final Property AccountGuid = new Property(NumberConstants.INT_2, String.class, "accountGuid", false, "ACCOUNT_GUID");

        public static final Property EncryptedData = new Property(NumberConstants.INT_3, byte[].class, "encryptedData", false,
                "ENCRYPTED_DATA");

        public static final Property Iv = new Property(NumberConstants.INT_4, byte[].class, "iv", false, "IV");

        public static final Property PublicKey = new Property(NumberConstants.INT_5, String.class, "publicKey", false, "PUBLIC_KEY");

        public static final Property OwnDevice = new Property(NumberConstants.INT_6, Boolean.class, "ownDevice", false, "OWN_DEVICE");

        public static final Property Attributes = new Property(NumberConstants.INT_7, String.class, "attributes", false, "ATTRIBUTES");
    }
}
