// Copyright (c) 2020-2021 ginlo.net GmbH

package eu.ginlo_apps.ginlo.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import eu.ginlo_apps.ginlo.greendao.AbstractSecureModel;

/**
 * Entity mapped to table NEW_DESTRUCTION_DATE.
 */
public class NewDestructionDate
        extends AbstractSecureModel
        implements java.io.Serializable {

    private Long mId;

    private String mGuid;

    private Long mNewDestructionDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NewDestructionDate() {
    }

    public NewDestructionDate(Long id) {
        this.mId = id;
    }

    public NewDestructionDate(Long id,
                              String guid,
                              Long newDestructionDate) {
        this.mId = id;
        this.mGuid = guid;
        this.mNewDestructionDate = newDestructionDate;
    }

    public Long getId() {
        return mId;
    }

    public void setId(Long id) {
        this.mId = id;
    }

    public String getGuid() {
        return mGuid;
    }

    public void setGuid(String guid) {
        this.mGuid = guid;
    }

    public Long getNewDestructionDate() {
        return mNewDestructionDate;
    }

    public void setNewDestructionDate(Long newDestructionDate) {
        this.mNewDestructionDate = newDestructionDate;
    }

    @Override
    public byte[] getEncryptedData() {
        return null;
    }

    @Override
    public void setEncryptedData(byte[] encryptedData) {
    }

    @Override
    public byte[] getIv() {
        return null;
    }

    @Override
    public void setIv(byte[] iv) {
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END
}
