// Copyright (c) 2020-2021 ginlo.net GmbH

package eu.ginlo_apps.ginlo.greendao;

import androidx.annotation.NonNull;
import eu.ginlo_apps.ginlo.exception.LocalizedException;
import eu.ginlo_apps.ginlo.greendao.AbstractSecureModel;
import eu.ginlo_apps.ginlo.greendao.GreenDAOSecurityLayer;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table STATUS_TEXT.
 */
public class StatusText
        extends AbstractSecureModel
        implements java.io.Serializable {

    private Long mId;

    private byte[] mEncryptedData;

    private byte[] mIv;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public StatusText() {
    }

    public StatusText(Long id) {
        this.mId = id;
    }

    public StatusText(Long id,
                      byte[] encryptedData,
                      byte[] iv) {
        this.mId = id;
        if (encryptedData != null) {
            this.mEncryptedData = encryptedData.clone();
        }
        if (iv != null) {
            this.mIv = iv.clone();
        }
    }

    public Long getId() {
        return mId;
    }

    public void setId(Long id) {
        this.mId = id;
    }

    public byte[] getEncryptedData() {
        if (mEncryptedData != null) {
            return mEncryptedData.clone();
        } else {
            return null;
        }
    }

    public void setEncryptedData(byte[] encryptedData) {
        if (encryptedData != null) {
            this.mEncryptedData = encryptedData.clone();
        }
    }

    public byte[] getIv() {
        if (mIv != null) {
            return mIv.clone();
        } else {
            return null;
        }
    }

    public void setIv(byte[] iv) {
        if (iv != null) {
            this.mIv = iv.clone();
        }
    }

    // KEEP METHODS - put your custom methods here

    /**
     * @throws LocalizedException [!EXC_DESCRIPTION!]
     */
    public String getText()
            throws LocalizedException {
        synchronized (this) {
            return (String) GreenDAOSecurityLayer.getInstance().get(this, "statusText");
        }
    }

    /**
     * @throws LocalizedException [!EXC_DESCRIPTION!]
     */
    public void setText(String statusText)
            throws LocalizedException {
        synchronized (this) {
            GreenDAOSecurityLayer.getInstance().set(this, "statusText", statusText);
        }
    }

    @NonNull
    @Override
    public String toString() {
        try {
            return getText();
        } catch (LocalizedException e) {
            return "";
        }
    }

    // KEEP METHODS END
}
